name: Build and deploy
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.19
        uses: actions/setup-go@v1
        with:
          go-version: 1.19
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          mkdir -p $GOPATH/bin
          export PATH=$PATH:$GOPATH/bin

      - name: Build
        run: go build -o bedrock_gopher -v cmd/main.go

      - name: Vet
        run: go vet ./...

      - name: Formatting
        run: test -z $(go fmt ./...)

      - name: Staticcheck
        run: |
          go get honnef.co/go/tools/cmd/staticcheck
          GOBIN=$PWD/bin go install honnef.co/go/tools/cmd/staticcheck
          ./bin/staticcheck ./...

  deploy:
    name: Deploy
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.19
        uses: actions/setup-go@v1
        with:
          go-version: 1.19
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          mkdir -p $GOPATH/bin
          export PATH=$PATH:$GOPATH/bin

      - name: Build
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: go build -o bedrock_gopher -v -ldflags "-X main.Token=$BOT_TOKEN" cmd/main.go

      - name: Set SSH info
        env:
          HOST: ${{ secrets.VPS_HOST }}
          SSH_KNOWN_HOSTS: ${{ secrets.VPS_KNOWN_HOSTS }}
          SSH_PRIVATE_KEY: ${{ secrets.VPS_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Stop bot
        env:
          HOST: ${{ secrets.VPS_HOST }}
        run: |
          ssh -i ~/.ssh/id_rsa $HOST screen -d -R -S bedrock_gopher -X stuff '^C'
          ssh -i ~/.ssh/id_rsa $HOST rm -f bedrock_gopher

      - name: Transfer executable
        env:
          HOST: ${{ secrets.VPS_HOST }}
          SSH_KNOWN_HOSTS: ${{ secrets.VPS_KNOWN_HOSTS }}
          SSH_PRIVATE_KEY: ${{ secrets.VPS_PRIVATE_KEY }}
        run: |
          scp -i ~/.ssh/id_rsa bedrock_gopher $HOST:/home/bedrock_gopher

      - name: Restart bot
        env:
          HOST: ${{ secrets.VPS_HOST }}
        run: |
          ssh -i ~/.ssh/id_rsa $HOST "screen -d -R -S bedrock_gopher -X stuff '/home/bedrock_gopher\n'"
